urls.py
from django.conf.urls.defaults import patterns
from satchmo_store.shop.satchmo_settings import get_satchmo_setting

ssl = get_satchmo_setting('SSL', default_value=False)

urlpatterns = patterns('',
    (r'^$', 'satchmo_stripe.views.pay_ship_info', {'SSL':ssl}, 'SATCHMO_STRIPE_satchmo_checkout-step2'),
    (r'^confirm/$','satchmo_stripe.views.confirm_info', {'SSL':ssl}, 'SATCHMO_STRIPE_satchmo_checkout-step3'),
    (r'^success/$', 'payment.views.checkout.success', {'SSL':ssl}, 'SATCHMO_STRIPE_checkout-success'),
)

models.py
from django.db import models
from django.utils.translation import ugettext as _

from satchmo_store.shop.models import Cart, Order, OrderPayment

import config
PAYMENT_PROCESSOR = True

class StripeToken(models.Model):
    orderpayment = models.ForeignKey(OrderPayment, unique=True, related_name="stripe_tokens")
    payment_token = models.CharField(_("Payment Token"), max_length=128, blank=True, null=True, editable=False)
    display_cc = models.CharField(_("CC Number (Last 4 digits)"), max_length=4,)

forms.py
import logging
from django import forms
from django.utils.translation import ugettext as _

from payment import signals
from payment.forms import SimplePayShipForm

from satchmo_store.contact.models import Contact
from satchmo_store.shop.models import Cart, Order, OrderPayment
from models import StripeToken

from signals_ahoy.signals import form_presave, form_postsave

log = logging.getLogger('payment.stripe.forms')

class StripePayShipForm(SimplePayShipForm):
    stripe_token = forms.CharField(max_length=50, widget=forms.HiddenInput({"value":""}))
    credit_number = forms.CharField(required=False)

    def __init__(self, request, paymentmodule, *args, **kwargs):
        super(StripePayShipForm, self).__init__(request, paymentmodule, *args, **kwargs)

        self.tempCart = Cart.objects.from_request(request)
        self.the_token = None

        try:
            self.tempContact = Contact.objects.from_request(request)
        except Contact.DoesNotExist:
            self.tempContact = None
        
    def clean_stripe_token(self):
        if len(self.cleaned_data['stripe_token']) == 0:
            raise forms.ValidationError(_('Invalid Stripe Token'))
        return self.cleaned_data['stripe_token']

    def save(self, request, cart, contact, payment_module, data=None):
        form_presave.send(StripePayShipForm, form=self)
        if data is None:
            data = self.cleaned_data
        assert(data)
        super(StripePayShipForm, self).save(request, cart, contact, payment_module, data=data)

        if self.orderpayment:
            op = self.orderpayment.capture
            token = StripeToken(
                orderpayment=op,
                payment_token = data['stripe_token'],)
            token.save()
            self.the_token = token
        form_postsave.send(StripePayShipForm, form=self)

views.py
from django import http
from django.shortcuts import render_to_response
from django.views.decorators.cache import never_cache
from django.template import Context, RequestContext
from django.template.loader import get_template

from satchmo_store.shop.models import Cart
from satchmo_store.shop.models import Order, OrderPayment
from satchmo_utils.dynamic import lookup_url, lookup_template

from livesettings import config_get_group, config_value
from payment.views import confirm, payship
from payment.config import gateway_live
from satchmo_stripe.forms import StripePayShipForm

import logging

log = logging.getLogger("satchmo_stripe.views")

stripe = config_get_group('PAYMENT_SATCHMO_STRIPE')

def stripe_pay_ship_process_form(request, contact, working_cart, payment_module, allow_skip=True, *args, **kwargs):
    def _get_form(request, payment_module, *args, **kwargs):
        return StripePayShipForm(request, payment_module, *args, **kwargs) 

    if request.method == "POST":
        new_data = request.POST.copy()
        form = _get_form(request, payment_module, new_data, *args, **kwargs)
        if form.is_valid():
            data = form.cleaned_data
            form.save(request, working_cart, contact, payment_module, data=data)
            url = lookup_url(payment_module, 'satchmo_checkout-step3')
            return (True, http.HttpResponseRedirect(url))
        else:
            pass
    else:
        order_data = {}
        try:
            order = Order.objects.from_request(request)
            if order.shipping_model:
                order_data['shipping'] = order.shipping_model
            if order.credit_card:
                # check if valid token
                pass

            kwargs['initial'] = order_data
            ordershippable = order.is_shippable
        except Order.DoesNotExist:
            pass

        form = _get_form(request, payment_module, *args, **kwargs)
        if not form.is_needed():
            form.save(request, working_cart, contact, None, data={'shipping', form.shipping_dict.keys()[0]})

            url = lookup_url(payment_module, 'satchmo_checkout-step3')
            return (True, http.HttpResponseRedirect(url))

    return (False, form)


def pay_ship_info(request):
    template = 'satchmo_stripe/pay_ship.html'
    payment_module = stripe
    form_handler = stripe_pay_ship_process_form
    result = payship.pay_ship_info_verify(request, payment_module)

    if not result[0]:
        return result[1]

    contact = result[1]
    working_cart = result[2]

    success, form = form_handler(request, contact, working_cart, payment_module)
    if success:
        return form

    template = lookup_template(payment_module, template)
    live = gateway_live(payment_module)

    ctx = RequestContext(request, {
        'form': form,
        'PAYMENT_LIVE': live,        
        })

    return render_to_response(template, context_instance=ctx)

    #return payship.base_pay_ship_info(request, stripe, stripe_pay_ship_process_form, "satchmo_stripe/pay_ship.html")
pay_ship_info = never_cache(pay_ship_info)

def confirm_info(request):
    payment_module = stripe
    controller = confirm.ConfirmController(request, payment_module)

    if not controller.sanity_check():
        return controller.response

    live = gateway_live(payment_module)

    default_view_tax = config_value('TAX', 'DEFAULT_VIEW_TAX')

    ctx = {
            'PAYMENT_LIVE': live
        }

    controller.extra_context = ctx
    controller.confirm()
    return controller.response

confirm_info = never_cache(confirm_info)

templates/satchmo_stripe/base_pay_ship.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block extra-head %}
<script type="text/javascript" src="/static/js/jquery-1.4.2.js"></script>
<script type="text/javascript" src="https://js.stripe.com/v1/"></script>
<script type="text/javascript" src="/static/js/stripe.js"></script>
{% endblock %}

{% block navbar %}
   <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
   <li>{% trans "Checkout" %}</li>
{% endblock %}

{% block content %}
<h3>{% trans "Checkout" %}</h3>
<div id="checkoutprogress">
<ul class="breadcrumb">
    <li class="first"><a href="{% url satchmo_checkout-step1 %}">{% trans "Ship/Bill" %}</a></li>
    <li class="active">{% trans "Payment" %}</li>
    <li>{% trans "Confirmation" %}</li>
</ul>
</div>

<h4>{% trans "Please complete the following information in order to submit your order." %}</h4>

{% if form.errors %}
    <h2>{% blocktrans count form.errors|length as count %}Please correct the following error:{% plural %}Please correct the following errors:{% endblocktrans %}</h2>
    {% if form.non_field_errors %}<p>
    {{ form.non_field_errors }}
    </p>{% endif %}
{% endif %}

<form method="post" action="." id="stripe-payment-form">{% csrf_token %}
<table>

    {% block payment_table %}
    {# put your payment module specific rows here.  For example, CC number. #}
    {% endblock %}
    
    {% if cart.is_shippable %}
    
            {% if form.shipping_hidden %}
                {{ form.shipping }}
                </table>
            {% else %}
            <tr><td><h4>{% trans "Shipping Information" %}</h4></td></tr>
                </table>
                {% block shipping_table %}
                <div id="shipping">
                {% if form.shipping_description or form.shipping.field.choices|length_is:1 %}
                <label for="id_shipping">{% trans "The following shipping method will be used" %}:</label>
                {% else %}
                <label for="id_shipping">{% trans "Please choose your preferred shipping method" %}</label>
                {% endif %}
                {{ form.shipping }}
                {% if form.shipping_description %}<br/>{{ form.shipping_description }}{% endif %}
                {% if form.shipping.errors %}*** {{ form.shipping.errors|join:", " }}{% endif %}
                </div>
                {% endblock %}
            {% endif %}

    {% else %}

        <tr><td colspan="2"><h4>{% trans "There are no items in this order to ship." %}</h4></td></tr>
        <tr><td colspan="2"> {{ form.shipping }} </td></tr>
    </table>

    {% endif %}
    
    {% if form.shipping.field.choices|length_is:0 and cart.is_shippable %}
        <h4>{% blocktrans %}No valid shipping method is available. Please verify that your address is correct.{% endblocktrans %}</h4>
    {% else %}
        <input type="submit" value="{% trans "Confirm" %}"/>
    {% endif %}
</form>

{% endblock %}

templates/satchmo_stripe/pay_ship.html
{% extends "satchmo_stripe/base_pay_ship.html" %}
{% load i18n %}
{# credit card pay_ship version - we just need to collect CC info #}

{% block payment_table %}
    <div id="stripe_error">
    </div>
    <tr><td><h4>{% trans "Payment Information" %}</h4></td></tr>
    {% if not PAYMENT_LIVE %}
    <tr><td valign="top"><b>TEST MODE</b></td><td><i>Use Visa 4111111111111111 for CC#<br/>any future date for expiration<br/>any 3 digit CCV</i></td></tr>
    {% endif %}

    <tr><td><label for="id_credit_number">{% trans "Credit card number" %}</label></td><td><input autocomplete="off" id="id_credit_number" type="text" name="" maxlength="20" /></td></tr>

    <tr><td><label for="id_month_expires">{% trans "Expiration date" %}</label><label for="id_year_expires"></label></td><td>
   <select name="" id="id_month_expires">
<option value="1">01</option>
<option value="2">02</option>
<option value="3">03</option>
<option value="4">04</option>
<option value="5">05</option>
<option value="6">06</option>
<option value="7">07</option>
<option value="8">08</option>
<option value="9">09</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
</select> <select name="" id="id_year_expires">
<option value="2012">2012</option>
<option value="2013">2013</option>
<option value="2014">2014</option>
<option value="2015">2015</option>
<option value="2016">2016</option>
<option value="2017">2017</option>
<option value="2018">2018</option>
<option value="2019">2019</option>
<option value="2020">2020</option>
<option value="2021">2021</option>
<option value="2022">2022</option>
</select>         
    </td></tr>

    <tr><td><label for="id_ccv">{% trans "CCV" %}</label></td><td><input autocomplete="off" id="id_ccv" type="text" name="" maxlength="4" /></td></tr>
    <input type="hidden" name="stripe_token" value="" id="id_stripe_token" />

{% endblock %}